# Generated by Django 5.2.5 on 2025-08-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DragAndDropQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answers', models.JSONField()),
                ('has_image', models.BooleanField(default=False)),
                ('image_filename', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('option_e', models.TextField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('has_image', models.BooleanField(default=False)),
                ('image_filename', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('option_e', models.TextField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('has_image', models.BooleanField(default=False)),
                ('image_filename', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
